import { useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronDown, ChevronRight, CircleHelp, ClipboardCopy, ExternalLink, GraduationCap, Heart, Home, Languages, Menu, MessageCircle, School, Search, Sparkles, X } from 'lucide-react'
import { activities, phrases, questions, type Activity, type Language } from './data/content'
import { Button, Card, Chip } from './components/ui'
import { cn } from './lib/utils'
import logo from './assets/linguaflow-family-logo.png'
import familyTutoring from './assets/family/family-tutoring.jpg'

type Page = 'today' | 'activities' | 'understand' | 'academy' | 'ask' | 'school'
const labels: Record<Language, Record<string, string>> = {
  en: { today: 'Today', activities: 'Activities', understand: 'Understand my child', academy: 'Parent Academy', ask: 'Ask an EAL expert', school: 'School connection', welcome: 'Small moments make a big difference.', welcomeSub: 'Simple, caring ways to help your child grow in English—while keeping your home language strong.', try: 'Try this tonight', minutes: 'minutes', start: 'Start activity', why: 'Why it helps', whyText: 'Everyday conversation builds vocabulary, confidence, and connection. There is no need to correct every word.', explore: 'Explore activities', all: 'All', search: 'Search activities', common: 'Common parent questions', wida: 'WIDA, in plain language', copy: 'Copy phrase', copied: 'Copied', askTitle: 'What would you like help with?', askSub: 'Choose a common question or search our EAL expert-reviewed answer library.', askPlaceholder: 'Try “Why is my child quiet at school?”', find: 'Find an answer', schoolTitle: 'Feel ready for the next school conversation.', schoolSub: 'Useful questions and phrases for talking with your child’s teacher.', meeting: 'Questions for a teacher meeting', language: 'Language' },
  zh: { today: '今天', activities: '亲子活动', understand: '了解我的孩子', academy: '家长课堂', ask: '咨询 EAL 专家', school: '学校沟通', welcome: '小小的陪伴，会带来大大的改变。', welcomeSub: '用简单温暖的方式帮助孩子学习英语，同时保持家庭语言的力量。', try: '今晚试一试', minutes: '分钟', start: '开始活动', why: '为什么有帮助', whyText: '日常对话可以培养词汇、信心和亲子连接。不需要纠正每一个词。', explore: '探索更多活动', all: '全部', search: '搜索活动', common: '家长常见问题', wida: '用简单的话了解 WIDA', copy: '复制短语', copied: '已复制', askTitle: '您希望获得哪方面的帮助？', askSub: '选择一个常见问题，或搜索由 EAL 专家审核的解答库。', askPlaceholder: '例如：“为什么孩子在学校很安静？”', find: '寻找答案', schoolTitle: '更有准备地与学校沟通。', schoolSub: '与孩子老师交流时可以使用的问题和短语。', meeting: '家长会可以问的问题', language: '语言' },
  ko: { today: '오늘', activities: '가족 활동', understand: '우리 아이 이해하기', academy: '부모 아카데미', ask: 'EAL 전문가에게 묻기', school: '학교와 소통하기', welcome: '작은 순간이 큰 변화를 만들어요.', welcomeSub: '가정의 언어를 소중히 지키며 아이의 영어 성장을 돕는 쉽고 따뜻한 방법이에요.', try: '오늘 저녁 해보기', minutes: '분', start: '활동 시작', why: '왜 도움이 되나요?', whyText: '일상 대화는 어휘, 자신감, 유대감을 키웁니다. 모든 단어를 고칠 필요는 없어요.', explore: '활동 둘러보기', all: '전체', search: '활동 검색', common: '부모님이 자주 묻는 질문', wida: '쉬운 말로 보는 WIDA', copy: '문구 복사', copied: '복사됨', askTitle: '어떤 도움이 필요하신가요?', askSub: '자주 묻는 질문을 고르거나 EAL 전문가가 검토한 답변을 검색해 보세요.', askPlaceholder: '예: “왜 아이가 학교에서 말이 없나요?”', find: '답변 찾기', schoolTitle: '학교와의 다음 대화를 준비하세요.', schoolSub: '선생님과 이야기할 때 유용한 질문과 문구입니다.', meeting: '선생님과 만날 때 물어볼 질문', language: '언어' },
}
const nav = [
  { id: 'today', icon: Home }, { id: 'activities', icon: Sparkles }, { id: 'understand', icon: Heart },
  { id: 'academy', icon: GraduationCap }, { id: 'ask', icon: MessageCircle }, { id: 'school', icon: School },
] as const
const languageNames = { en: 'English', zh: '中文', ko: '한국어' }

function App() {
  const [lang, setLang] = useState<Language>('en')
  const [page, setPage] = useState<Page>('today')
  const [menu, setMenu] = useState(false)
  const [selected, setSelected] = useState<Activity | null>(null)
  const t = labels[lang]
  const go = (next: Page) => { setPage(next); setMenu(false); setSelected(null); window.scrollTo(0, 0) }
  return <div className="min-h-screen">
    <header className="sticky top-0 z-40 border-b border-stone-200/70 bg-[#f7f8fc]/90 backdrop-blur-xl">
      <div className="mx-auto flex h-16 max-w-6xl items-center gap-3 px-4 md:h-20 md:px-8">
        <button onClick={() => go('today')} className="flex items-center gap-2.5 rounded-xl text-left focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-teal-700/20" aria-label="LinguaFlow Family home">
          <span className="grid size-11 place-items-center rounded-2xl bg-white shadow-[0_7px_18px_rgba(60,132,205,.16)]"><img src={logo} alt="" className="size-10 object-contain" /></span>
          <span className="hidden font-extrabold leading-tight text-stone-800 sm:block">LinguaFlow<br/><span className="lf-gradient-text">Family</span></span>
        </button>
        <nav className="ml-4 hidden flex-1 items-center justify-center gap-1 lg:flex" aria-label="Main navigation">
          {nav.map(({ id, icon: Icon }) => <button key={id} onClick={() => go(id)} className={cn('flex min-h-11 items-center gap-2 rounded-full px-3.5 text-sm font-bold transition', page === id ? 'bg-teal-50 text-teal-800' : 'text-stone-600 hover:bg-stone-100')}><Icon size={17}/>{t[id]}</button>)}
        </nav>
        <label className="ml-auto flex items-center gap-2 rounded-full border border-stone-200 bg-white px-3 shadow-sm">
          <Languages size={17} className="text-teal-700"/><span className="sr-only">{t.language}</span>
          <select value={lang} onChange={e => setLang(e.target.value as Language)} className="min-h-10 appearance-none bg-transparent pr-5 text-sm font-bold outline-none" aria-label={t.language}>
            {Object.entries(languageNames).map(([code, name]) => <option key={code} value={code}>{name}</option>)}
          </select><ChevronDown size={14} className="-ml-6 pointer-events-none"/>
        </label>
        <button onClick={() => setMenu(!menu)} className="grid size-11 place-items-center rounded-full hover:bg-stone-100 lg:hidden" aria-label="Open menu" aria-expanded={menu}>{menu ? <X/> : <Menu/>}</button>
      </div>
      {menu && <nav className="border-t border-stone-200 bg-white p-3 lg:hidden" aria-label="Mobile navigation">{nav.map(({ id, icon: Icon }) => <button key={id} onClick={() => go(id)} className={cn('flex min-h-12 w-full items-center gap-3 rounded-xl px-4 text-left font-bold', page === id ? 'bg-teal-50 text-teal-800' : 'text-stone-700')}><Icon size={19}/>{t[id]}</button>)}</nav>}
    </header>
    <main>
      {selected ? <ActivityDetail activity={selected} lang={lang} t={t} back={() => setSelected(null)}/> : <PageContent page={page} lang={lang} t={t} go={go} select={setSelected}/>} 
    </main>
    <footer className="border-t border-stone-200 bg-white px-5 py-10 text-center text-sm text-stone-500"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-3 sm:flex-row"><span className="font-bold text-stone-700">LinguaFlow <span className="lf-gradient-text">Family</span></span><span>Home language is a strength. · 家庭语言是一种力量。 · 가정의 언어는 힘입니다.</span><a href="https://www.mymultilingualfamily.com/" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-1.5 font-bold text-teal-700 hover:text-teal-800">{lang==='en'?'Full family guide':lang==='zh'?'完整家庭指南':'전체 가족 가이드'}<ExternalLink size={15}/></a></div></footer>
  </div>
}

function PageContent({ page, lang, t, go, select }: { page: Page; lang: Language; t: Record<string,string>; go: (p: Page)=>void; select: (a: Activity)=>void }) {
  if (page === 'today') return <Today lang={lang} t={t} go={go} select={select}/>
  if (page === 'activities') return <Activities lang={lang} t={t} select={select}/>
  if (page === 'understand') return <Understand lang={lang} t={t}/>
  if (page === 'academy') return <Academy lang={lang} t={t}/>
  if (page === 'ask') return <Ask lang={lang} t={t}/>
  return <SchoolPage lang={lang} t={t}/>
}

function Today({ lang, t, go, select }: { lang: Language; t: Record<string,string>; go: (p:Page)=>void; select:(a:Activity)=>void }) {
  const featured = activities[1]
  return <>
    <section className="overflow-hidden px-4 pb-12 pt-10 md:px-8 md:pb-20 md:pt-16"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1.1fr_.9fr]">
      <div><Chip className="mb-5 bg-teal-50 text-teal-800"><Sparkles size={14} className="mr-1.5"/>{t.try}</Chip><h1 className="font-display max-w-3xl text-balance text-4xl font-bold leading-[1.04] tracking-[-.035em] text-stone-800 md:text-6xl">{t.welcome}</h1><p className="mt-5 max-w-2xl text-balance text-lg leading-8 text-stone-600 md:text-xl">{t.welcomeSub}</p></div>
      <Card className="lf-hero relative overflow-hidden border-0 text-white shadow-[0_25px_60px_rgba(62,91,174,.24)]"><div className="relative h-48 overflow-hidden md:h-56"><img src={featured.image} alt={featured.imageAlt[lang]} className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#1f638d]/80 via-transparent to-transparent"/><Chip className="absolute right-5 top-5 bg-white/90 text-stone-700 shadow-sm">{featured.time}</Chip></div><div className="relative p-6 md:p-8"><p className="text-sm font-bold uppercase tracking-[.14em] text-white/75">{t.try}</p><h2 className="font-display mt-2 text-3xl font-bold">{featured.title[lang]}</h2><p className="mt-3 leading-7 text-white/85">{featured.summary[lang]}</p><Button onClick={() => select(featured)} className="mt-7 w-full bg-white !bg-none text-stone-800 shadow-sm hover:bg-white/90">{t.start}<ArrowRight size={18}/></Button></div></Card>
    </div></section>
    <section className="px-4 pb-12 md:px-8 md:pb-16"><div className="mx-auto max-w-6xl"><p className="text-sm font-black uppercase tracking-[.14em] text-teal-700">{lang==='en'?'Start with what you need':lang==='zh'?'从您现在需要的开始':'지금 필요한 것부터 시작하세요'}</p><h2 className="font-display mt-2 text-3xl font-bold text-stone-800">{lang==='en'?'What would help today?':lang==='zh'?'今天什么最能帮助您？':'오늘 어떤 도움이 필요하신가요?'}</h2><div className="mt-6 grid gap-3 md:grid-cols-3">
      <button onClick={()=>select(featured)} className="group flex min-h-24 items-center gap-4 rounded-2xl border border-stone-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-700"><Sparkles size={21}/></span><span className="flex-1"><strong className="block text-stone-800">{lang==='en'?'Something to do tonight':lang==='zh'?'今晚可以做的活动':'오늘 저녁에 할 활동'}</strong><span className="mt-1 block text-sm text-stone-500">{t.try}</span></span><ChevronRight className="text-stone-300 transition group-hover:translate-x-1"/></button>
      <button onClick={()=>go('ask')} className="group flex min-h-24 items-center gap-4 rounded-2xl border border-stone-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-700"><MessageCircle size={21}/></span><span className="flex-1"><strong className="block text-stone-800">{lang==='en'?'A question about my child':lang==='zh'?'关于孩子的问题':'아이에 관한 질문'}</strong><span className="mt-1 block text-sm text-stone-500">{t.ask}</span></span><ChevronRight className="text-stone-300 transition group-hover:translate-x-1"/></button>
      <button onClick={()=>go('school')} className="group flex min-h-24 items-center gap-4 rounded-2xl border border-stone-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-700"><School size={21}/></span><span className="flex-1"><strong className="block text-stone-800">{lang==='en'?'Help talking with school':lang==='zh'?'帮助我与学校沟通':'학교와 대화하는 데 도움'}</strong><span className="mt-1 block text-sm text-stone-500">{t.school}</span></span><ChevronRight className="text-stone-300 transition group-hover:translate-x-1"/></button>
    </div></div></section>
    <section className="px-4 pb-12 md:px-8 md:pb-16"><div className="mx-auto max-w-6xl"><div className="grid overflow-hidden rounded-[2rem] border border-white/80 bg-white/75 shadow-[0_18px_50px_rgba(52,63,99,.08)] backdrop-blur md:grid-cols-[.9fr_1.1fr]">
      <div className="grid min-h-64 grid-cols-2 gap-1 bg-stone-100 md:min-h-72"><img src={familyTutoring} alt={lang==='en'?'A school-age child learning with a trusted adult at home':lang==='zh'?'一名学龄儿童在家与可信赖的成年人一起学习':'학령기 아이가 집에서 믿을 수 있는 어른과 함께 배우는 모습'} loading="lazy" className="h-full w-full object-cover"/><img src={activities[2].image} alt={activities[2].imageAlt[lang]} loading="lazy" className="h-full w-full object-cover"/></div>
      <div className="flex flex-col justify-center p-7 md:p-10"><p className="text-sm font-black uppercase tracking-[.14em] text-teal-700">{lang==='en'?'Every family belongs':lang==='zh'?'每个家庭都属于这里':'모든 가족을 위한 공간'}</p><h2 className="font-display mt-3 text-3xl font-bold tracking-tight text-stone-800 md:text-4xl">{lang==='en'?'Your language. Your stories. Your strength.':lang==='zh'?'您的语言、您的故事、您的力量。':'우리의 언어, 이야기, 그리고 힘.'}</h2><p className="mt-4 max-w-xl leading-7 text-stone-600">{lang==='en'?'Children grow when families talk, read, laugh, and wonder together—in any language. LinguaFlow Family starts with what you already do well.':lang==='zh'?'当家人用任何语言一起交谈、阅读、欢笑和探索时，孩子都会成长。LinguaFlow Family 从您已经做得很好的事情开始。':'가족이 어떤 언어로든 함께 이야기하고, 읽고, 웃고, 궁금해할 때 아이는 자랍니다. LinguaFlow Family는 이미 잘하고 계신 것에서 시작해요.'}</p></div>
    </div></div></section>
    <section className="border-y border-stone-200/70 bg-white/55 px-4 py-12 md:px-8 md:py-16"><div className="mx-auto max-w-6xl"><div className="mb-7 flex items-end justify-between"><div><p className="font-bold text-teal-700">10–15 {t.minutes}</p><h2 className="font-display mt-1 text-3xl font-bold tracking-tight text-stone-800">{t.explore}</h2></div><button onClick={() => go('activities')} className="hidden items-center gap-1 font-bold text-teal-700 sm:flex">{t.all}<ChevronRight size={18}/></button></div><div className="grid gap-4 md:grid-cols-3">{activities.slice(1,4).map(a => <ActivityCard key={a.id} activity={a} lang={lang} onClick={() => select(a)}/>)}</div><Button onClick={() => go('activities')} className="mt-6 w-full sm:hidden">{t.explore}</Button></div></section>
  </>
}

function ActivityCard({ activity, lang, onClick }: { activity: Activity; lang: Language; onClick:()=>void }) { return <Card onClick={onClick} className="group cursor-pointer overflow-hidden transition hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(52,63,99,.12)]"><div className="relative h-44 overflow-hidden bg-stone-100"><img src={activity.image} alt={activity.imageAlt[lang]} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]"/><span className="absolute bottom-3 left-3 grid size-10 place-items-center rounded-xl bg-white/90 text-xl shadow-sm backdrop-blur">{activity.icon}</span></div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-xl font-black text-stone-800">{activity.title[lang]}</h3><ArrowRight className="shrink-0 text-stone-300 transition group-hover:translate-x-1 group-hover:text-teal-700"/></div><p className="mt-2 min-h-12 text-sm leading-6 text-stone-600">{activity.summary[lang]}</p><div className="mt-4 flex gap-2"><Chip>{activity.time}</Chip><Chip className="bg-teal-50 text-teal-800">{activity.skill[lang]}</Chip></div></div></Card> }

function Activities({ lang, t, select }: { lang: Language; t: Record<string,string>; select:(a:Activity)=>void }) { const [search,setSearch]=useState(''); const list=useMemo(()=>activities.filter(a => `${a.title[lang]} ${a.summary[lang]}`.toLowerCase().includes(search.toLowerCase())),[search,lang]); return <PageShell eyebrow={t.activities} title={lang==='en'?'Easy ways to learn together.':lang==='zh'?'一起学习，可以很简单。':'함께 배우는 쉬운 방법이에요.'} subtitle={lang==='en'?'No worksheets. No English expertise needed. Choose one activity and make it your own.':lang==='zh'?'不需要练习册，也不要求您精通英语。选择一个活动，用适合自己家庭的方式来做。':'학습지도, 뛰어난 영어 실력도 필요 없어요. 활동 하나를 골라 우리 가족답게 해보세요.'}><div className="relative mb-7 max-w-lg"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-stone-400" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t.search} className="min-h-13 w-full rounded-2xl border border-stone-200 bg-white pl-12 pr-4 outline-none focus:ring-4 focus:ring-teal-700/15"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{list.map(a=><ActivityCard key={a.id} activity={a} lang={lang} onClick={()=>select(a)}/>)}</div></PageShell> }

function ActivityDetail({ activity, lang, t, back }: { activity:Activity; lang:Language; t:Record<string,string>; back:()=>void }) { return <PageShell eyebrow={activity.skill[lang]} title={activity.title[lang]} subtitle={activity.summary[lang]}><button onClick={back} className="mb-7 flex min-h-11 items-center gap-2 font-bold text-teal-700"><ArrowLeft size={18}/>{t.activities}</button><div className="grid gap-6 lg:grid-cols-[1fr_.55fr]"><Card className="overflow-hidden"><img src={activity.image} alt={activity.imageAlt[lang]} className="h-56 w-full object-cover md:h-72"/><div className="p-6 md:p-8"><div className="mb-7 flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-amber-50 text-2xl">{activity.icon}</span><div><Chip>{activity.time}</Chip><p className="mt-2 font-bold text-stone-500">{activity.skill[lang]}</p></div></div><ol className="space-y-5">{activity.steps.map((s,i)=><li key={i} className="flex gap-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-teal-700 text-sm font-black text-white">{i+1}</span><p className="pt-1 leading-7 text-stone-700">{s[lang]}</p></li>)}</ol></div></Card><Card className="h-fit bg-amber-50 p-6"><p className="text-sm font-black uppercase tracking-wider text-amber-900">{t.why}</p><p className="mt-3 leading-7 text-stone-700">{t.whyText}</p><div className="mt-6 rounded-2xl bg-white p-5"><MessageCircle size={20} className="text-teal-700"/><p className="mt-3 text-lg font-black text-stone-800">“{activity.phrase[lang]}”</p></div></Card></div></PageShell> }

function Understand({ lang, t }: { lang:Language;t:Record<string,string> }) { return <PageShell eyebrow={t.understand} title={lang==='en'?'Language growth is a journey, not a race.':lang==='zh'?'语言成长是一段旅程，不是一场比赛。':'언어 성장은 경주가 아니라 여정입니다.'} subtitle={lang==='en'?'Clear, reassuring explanations for the questions families ask most.':lang==='zh'?'为家长最关心的问题提供清晰、安心的解释。':'가족들이 가장 많이 묻는 질문에 명확하고 안심되는 설명을 드려요.'}><div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><Card className="h-fit overflow-hidden bg-teal-800 text-white"><img src={activities[3].image} alt={activities[3].imageAlt[lang]} loading="lazy" className="h-48 w-full object-cover object-center"/><div className="p-6 md:p-8"><BookOpen size={28}/><h2 className="mt-5 text-2xl font-black">{t.wida}</h2><p className="mt-4 leading-7 text-teal-50">{questions[3].a[lang]}</p><div className="mt-6 flex flex-wrap gap-2">{['Listening','Speaking','Reading','Writing'].map(x=><Chip key={x} className="bg-white/12 text-white">{x}</Chip>)}</div></div></Card><div><h2 className="mb-4 text-2xl font-black text-stone-800">{t.common}</h2><Accordion lang={lang}/></div></div></PageShell> }
function Accordion({lang}:{lang:Language}) { const [open,setOpen]=useState(0); return <div className="space-y-3">{questions.map((item,i)=><Card key={i} className="overflow-hidden"><button onClick={()=>setOpen(open===i?-1:i)} className="flex min-h-16 w-full items-center justify-between gap-4 p-5 text-left font-black text-stone-800"><span>{item.q[lang]}</span><ChevronDown className={cn('shrink-0 transition',open===i&&'rotate-180')}/></button>{open===i&&<p className="border-t border-stone-100 px-5 py-5 leading-7 text-stone-600">{item.a[lang]}</p>}</Card>)}</div> }

function Academy({lang,t}:{lang:Language;t:Record<string,string>}) { const lessons=[{icon:'🌱',title:{en:'Your home language is a superpower',zh:'家庭语言是孩子的超能力',ko:'가정의 언어는 아이의 특별한 힘이에요'},text:{en:'How strong first-language skills support English and learning.',zh:'了解扎实的第一语言如何帮助英语学习和整体成长。',ko:'탄탄한 모국어가 영어와 학습을 어떻게 돕는지 알아보세요.'}},{icon:'💬',title:{en:'Talk that grows thinking',zh:'用对话培养思考力',ko:'생각을 키우는 대화'},text:{en:'Simple ways to invite longer, richer answers.',zh:'用简单的方法鼓励孩子给出更丰富、更完整的回答。',ko:'더 길고 풍부한 대답을 이끄는 쉬운 방법이에요.'}},{icon:'📚',title:{en:'Read together, your way',zh:'用适合您家庭的方式一起阅读',ko:'우리 가족만의 방식으로 함께 읽기'},text:{en:'Make any book meaningful—even when it is not in English.',zh:'让任何一本书都有意义——即使它不是英文书。',ko:'영어책이 아니어도 모든 책을 의미 있게 읽을 수 있어요.'}}]; return <PageShell eyebrow={t.academy} title={lang==='en'?'Short lessons. Lasting confidence.':lang==='zh'?'简短课程，带来长久信心。':'짧은 배움으로 오래가는 자신감을.'} subtitle={lang==='en'?'Friendly, research-informed guidance you can use right away.':lang==='zh'?'亲切、可靠，而且马上就能用的家长指南。':'연구에 기반한 친절한 안내를 바로 활용해 보세요.'}><Card className="mb-6 grid overflow-hidden md:grid-cols-[.85fr_1.15fr]"><img src={activities[4].image} alt={activities[4].imageAlt[lang]} loading="lazy" className="h-56 w-full object-cover md:h-full"/><div className="flex flex-col justify-center p-6 md:p-8"><Chip className="w-fit bg-teal-50 text-teal-800">{lang==='en'?'Made for real family life':lang==='zh'?'为真实的家庭生活而设计':'실제 가족의 일상을 위해'}</Chip><h2 className="font-display mt-4 text-3xl font-bold text-stone-800">{lang==='en'?'You do not have to become the teacher.':lang==='zh'?'您不必成为老师。':'부모님이 선생님이 될 필요는 없어요.'}</h2><p className="mt-3 leading-7 text-stone-600">{lang==='en'?'Your role is connection: noticing, listening, asking, and encouraging. These short lessons help you do that with confidence.':lang==='zh'?'您的角色是建立连接：观察、倾听、提问和鼓励。这些简短课程帮助您更有信心地做到这一点。':'부모님의 역할은 연결입니다. 살펴보고, 듣고, 질문하고, 격려해 주세요. 짧은 수업이 자신 있게 실천하도록 도와드려요.'}</p></div></Card><div className="grid gap-4 md:grid-cols-3">{lessons.map((x,i)=><Card key={i} className="p-6"><span className="text-3xl">{x.icon}</span><p className="mt-5 text-xs font-black uppercase tracking-wider text-teal-700">{lang==='en'?`Lesson ${i+1}`:lang==='zh'?`第 ${i+1} 课`:`${i+1}강`}</p><h2 className="mt-2 text-xl font-black text-stone-800">{x.title[lang]}</h2><p className="mt-3 leading-7 text-stone-600">{x.text[lang]}</p><button className="mt-5 flex min-h-11 items-center gap-2 font-bold text-teal-700">{lang==='en'?'Read lesson':lang==='zh'?'阅读课程':'수업 읽기'}<ArrowRight size={17}/></button></Card>)}</div></PageShell> }

function Ask({lang,t}:{lang:Language;t:Record<string,string>}) { const [query,setQuery]=useState(''); const [answer,setAnswer]=useState<typeof questions[0]|null>(null); const find=(question=query)=>{setQuery(question);const words=question.toLowerCase().split(/\s+/); setAnswer(questions.find(x=>words.some(w=>w.length>2&&`${x.q[lang]} ${x.a[lang]}`.toLowerCase().includes(w)))??questions[0])}; return <PageShell eyebrow={t.ask} title={t.askTitle} subtitle={t.askSub}><div className="mx-auto max-w-3xl"><Card className="p-5 md:p-8"><p className="text-sm font-black uppercase tracking-[.12em] text-teal-700">{lang==='en'?'Start with one question':lang==='zh'?'从一个问题开始':'질문 하나로 시작하세요'}</p><div className="mt-4 flex flex-wrap gap-2">{questions.slice(0,3).map(item=><button key={item.q.en} onClick={()=>find(item.q[lang])} className="min-h-11 rounded-full border border-stone-200 bg-white px-4 text-left text-sm font-bold text-stone-700 transition hover:border-teal-700 hover:text-teal-800">{item.q[lang]}</button>)}</div><label className="mt-7 block font-black text-stone-800" htmlFor="parent-question">{lang==='en'?'Or search in your own words':lang==='zh'?'或者用您自己的话搜索':'또는 직접 검색해 보세요'}</label><div className="mt-3 flex flex-col gap-3 sm:flex-row"><input id="parent-question" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&find()} placeholder={t.askPlaceholder} className="min-h-13 flex-1 rounded-2xl border border-stone-200 px-4 outline-none focus:ring-4 focus:ring-teal-700/15"/><Button onClick={()=>find()}><Search size={18}/>{t.find}</Button></div>{answer&&<div className="mt-7 rounded-2xl bg-teal-50 p-5 md:p-6"><div className="flex gap-3"><CircleHelp className="mt-1 shrink-0 text-teal-700"/><div><h2 className="text-lg font-black text-stone-800">{answer.q[lang]}</h2><p className="mt-3 leading-7 text-stone-700">{answer.a[lang]}</p><p className="mt-4 text-sm font-bold text-teal-800">{lang==='en'?'A helpful next step: share this question with your child’s teacher.':lang==='zh'?'下一步建议：也可以把这个问题告诉孩子的老师。':'도움이 되는 다음 단계: 이 질문을 아이의 선생님과 나눠보세요.'}</p></div></div></div>}</Card><a href="https://www.mymultilingualfamily.com/" target="_blank" rel="noreferrer" className="mt-4 flex min-h-20 items-center gap-4 rounded-2xl border border-stone-200 bg-white p-5 text-stone-700 shadow-sm transition hover:border-teal-700"><BookOpen className="shrink-0 text-teal-700"/><span className="flex-1"><strong className="block text-stone-800">{lang==='en'?'Explore the full family guide':lang==='zh'?'浏览完整的家庭指南':'전체 가족 가이드 살펴보기'}</strong><span className="mt-1 block text-sm text-stone-500">My Multilingual Family</span></span><ExternalLink size={18}/></a></div></PageShell> }

function SchoolPage({lang,t}:{lang:Language;t:Record<string,string>}) { const [copied,setCopied]=useState(''); const meeting:Record<Language,string[]>={en:['What is my child doing well?','When does my child feel most confident?','What is one thing we can practice at home?'],zh:['我的孩子在哪些方面做得很好？','孩子什么时候最有信心？','我们可以在家练习哪一件事？'],ko:['우리 아이가 잘하고 있는 것은 무엇인가요?','아이가 언제 가장 자신감을 보이나요?','집에서 연습할 수 있는 한 가지는 무엇인가요?']}; const copy=(text:string)=>{navigator.clipboard?.writeText(text);setCopied(text);setTimeout(()=>setCopied(''),1600)}; return <PageShell eyebrow={t.school} title={t.schoolTitle} subtitle={t.schoolSub}><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="h-fit bg-amber-50 p-6"><School className="text-amber-800"/><h2 className="mt-4 text-xl font-black text-stone-800">{t.meeting}</h2><ul className="mt-5 space-y-4">{meeting[lang].map(x=><li key={x} className="flex gap-3"><span className="grid size-6 shrink-0 place-items-center rounded-full bg-white text-teal-700"><Check size={14}/></span><span className="leading-6 text-stone-700">{x}</span></li>)}</ul></Card><div className="space-y-3">{phrases.map(p=>{const text=p[lang];return <Card key={p.en} className="flex items-center gap-4 p-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-teal-50"><Languages size={19} className="text-teal-700"/></span><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-wider text-stone-400">{p.category}</p><p className="mt-1 font-bold text-stone-800">{text}</p>{lang!=='en'&&<p className="mt-1 text-sm text-stone-500">{p.en}</p>}</div><button onClick={()=>copy(text)} className="grid size-11 shrink-0 place-items-center rounded-full hover:bg-stone-100" aria-label={t.copy}>{copied===text?<Check className="text-teal-700" size={19}/>:<ClipboardCopy size={19}/>}</button></Card>})}</div></div></PageShell> }

function PageShell({eyebrow,title,subtitle,children}:{eyebrow:string;title:string;subtitle:string;children:React.ReactNode}) { return <div className="px-4 py-10 md:px-8 md:py-16"><div className="mx-auto max-w-6xl"><p className="font-black text-teal-700">{eyebrow}</p><h1 className="font-display mt-3 max-w-3xl text-balance text-4xl font-bold tracking-[-.03em] text-stone-800 md:text-5xl">{title}</h1><p className="mt-4 mb-10 max-w-2xl text-lg leading-8 text-stone-600">{subtitle}</p>{children}</div></div> }

export default App
